version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appointments
    volumes:
      - ./.volumes/mysql_data:/var/lib/mysql
      - ./scripts/mysql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./.volumes/redis_data:/data
